engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript:
        - php:
  eslint:
    enabled: true
  phpcodesniffer:
    enabled: true
    exclude_paths:
      - database/migrations/**/*
  phpmd:
    enabled: true
    checks:
      Naming/ShortMethodName:
        enabled: false
    exclude_paths:
      - tests/**/*
  scss-lint:
    enabled: true

ratings:
  paths:
    - "**.js"
    - "**.php"
    - "**.scss"

exclude_paths:
  - bootstrap/**/*
  - resources/views/**/*
