engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript:
        - php:
    exclude_paths:
      - spec/**/*
  eslint:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Naming/ShortMethodName:
        enabled: false
  scss-lint:
    enabled: true

ratings:
  paths:
    - "**.js"
    - "**.php"
    - "**.scss"
